# Generated by Django 3.2 on 2021-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=40)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
